---
services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    ports:
      - 8239:9001
      - 18443:8443
    deploy:
      mode: global
      restart_policy:
        condition: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio.entrypoints=websecure"
      - "traefik.http.routers.drawio.rule=Host(`drawio.lan.dresen.tech`)"
      - "traefik.http.routers.drawio.tls=true"
      - "traefik.http.routers.drawio.tls.certresolver=production"
    networks:
      - docker_net
networks:
    docker_net:
      external: true

