---
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      # Set the timezone to your local timezone
      - TZ=America/New_York
    ports:
      - '8945:8945'
    volumes:
      - /home/sdresen/docker/pinchflat/config:/config
      - /mnt/zeus-dockerdata/pinchflat/downloads:/downloads
    deploy:
      mode: global
      restart_policy:
        condition: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pinchflat.entrypoints=websecure"
      - "traefik.http.routers.pinchflat.rule=Host(`pinchflat.lan.dresen.tech`)"
      - "traefik.http.routers.pinchflat.tls=true"
      - "traefik.http.routers.pinchflat.tls.certresolver=production"
    networks:
      - docker_net
networks:
    docker_net:
      external: true

