services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    container_name: broadlinkmanager
    volumes:
      - ./broadlinkmanager:/opt/broadlinkmanager/data
    ports:
      - 7020:7020
    environment:
      - ENABLE_GOOGLE_ANALYTICS=False #Optional, default is True, Set to False if you want to disable Google Analytics
    deploy:
      mode: global
      restart_policy:
        condition: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.broadlink.entrypoints=websecure"
      - "traefik.http.routers.broadlink.rule=Host(`broadlink.lan.dresen.tech`)"
      - "traefik.http.routers.broadlink.tls=true"
      - "traefik.http.routers.broadlink.tls.certresolver=production"
    networks:
      - docker_net
networks:
    docker_net:
      external: true
