---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    url: https://whoogle.lan.dresen.tech//search?q=
    target: _blank

- datetime:
    text_size: md
    # 1/23/22, 1:37 PM
    format:
      dateStyle: short
      timeStyle: short
      hour12: true

